### ISSUE TITLE
Que tal a remoção de arquivos ou diretórios indesejados do histórico do repositório?

### ISSUE THREAD

**Issue by tacianosilva** [joaoarthurbm/designwizard#13]
Olá @joaoarthurbm e @Gustavohqo,

Quando fui analizar o porquê de tantos arquivos ao comparar o branch do meu fork com o branch original de joão notei que existem inúmeros diretórios .svn no projeto. Creio que eu os tenha deletado no meu fork.

Seria interessante remover esses arquivos de todo o histórico do repositório do design wizard?

Acho que não é complicado, vejam nos links: 
* https://help.github.com/articles/remove-sensitive-data/
* https://rtyley.github.io/bfg-repo-cleaner/

Acho que isso deixaria a comparação com os forks com poucos arquivos modificados.

**Comment by joaoarthurbm** [comment]
Oi @tacianosilva , eu apaguei os arquivos relacionados ao svn. Pode checar agora para eu fechar a issue?

**Comment by tacianosilva** [comment]
@joaoarthurbm no HEAD atual não encontrei arquivos relacionados ao svn.
